dist: trusty
sudo: false
language: node_js
node_js:
- 12
after_success:
- "./node_modules/.bin/codecov"
deploy:
  provider: npm
  email: opensource@wayfair.com
  api_key:
    secure: EP1QvdDYjS8si7BpTs96Uz/atftKJVKyFTgh+WSKLcLjRt4boCSJvEZ49EgAG9OWy4NU2I1CDyK0Z7Illrd6rPfWipJdLUFZjlKQoeG0zymCM7Xe+UdK/sD4ODQsC1N1OfssaMFO1JDT4LWJxPZyycIoaXaJW2pnzoNVbkHzhBMNRT04KnJY4d6YXzNQr2bKUlyR2n1EkJA9Hdhhph9WNwS0agH0ddWJbJL4rIoAvWmbITqvuUhH+o6M9I9xlG25r5q3SMT4z7G5HRJt9KTirflUiJQgfOoFzJe9hVDH78HHAClBcBwnHYKNs5eo0R9iZmCOcLRTvP+v5rETB7VjV09kWq1QY7PapZduT8sCZqOCLiIVJo68bZ3RvS8AbSGUAiMMiwlfIGJcJCPTwnujUrnsigNcd0n/uL4XEYxOY5gRBBw62DktzuHglY9xWRFKWltId0kwP9jIaKGgQnAYJCfGV145injRiyTJGB+T9GBmydvEPl9L49eBNWDbg5c5oUQ7Gn4SXwXPY7GeCKjAL8t+0NcMif7xW88ot8lezc0HDPP+pRCTbhDM0smew9uMQlZFFCQLgR1PCmNBdPhhCJfmNkpskXj6HA3/eOGxThkoid+4k7gdF9gVriDIpW79XPctofxLI1taeo/BHyrejr3YBTFISLSGSWGZjPMvvLo=
  on:
    tags: true
    repo: wayfair/dociql
    branch: master
