spectaql:
  logoFile: ./test/fixtures/logo.png
  faviconFile: ./test/fixtures/favicon.png

introspection:
  # url: http://localhost:3000/graphql
  schemaFile: ./examples/data/schema.gql
  # introspectionFile: ./examples/data/introspection-with-metadata.json
  # metadataFile: ./examples/data/metadata.json
  dynamicExamplesProcessingModule: ./examples/customizations/examples

info:
  title: GraphQL API Reference
  description: Welcome to the party!
  termsOfService: https://www.example.com/terms
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://example.com/graphql
    description: Production
    production: true
